// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS-bS2C_YC3vjj5Prwe7T3szIT5PCmnt8',
    appId: '1:251001959745:web:5b17e568780deb1a519dc0',
    messagingSenderId: '251001959745',
    projectId: 'child-safety-app-2b13d',
    authDomain: 'child-safety-app-2b13d.firebaseapp.com',
    storageBucket: 'child-safety-app-2b13d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfCKVXKbCLZIF6tk9KqVa43nxj5o_hMZM',
    appId: '1:251001959745:android:77c129b99ddafb7d519dc0',
    messagingSenderId: '251001959745',
    projectId: 'child-safety-app-2b13d',
    storageBucket: 'child-safety-app-2b13d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM9UhcC-tQ-gsQKIVnxsWTFqz1imeJvlg',
    appId: '1:251001959745:ios:9856c56bf279605c519dc0',
    messagingSenderId: '251001959745',
    projectId: 'child-safety-app-2b13d',
    storageBucket: 'child-safety-app-2b13d.firebasestorage.app',
    iosBundleId: 'com.example.childSafety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS-bS2C_YC3vjj5Prwe7T3szIT5PCmnt8',
    appId: '1:251001959745:web:4ff4960a66e9bb8a519dc0',
    messagingSenderId: '251001959745',
    projectId: 'child-safety-app-2b13d',
    authDomain: 'child-safety-app-2b13d.firebaseapp.com',
    storageBucket: 'child-safety-app-2b13d.firebasestorage.app',
  );
}
